### ISSUE TITLE
build error when following README.md

### ISSUE THREAD

**Issue by yatesco** [yurique/scala-js-laminar-starter.g8#16]
Hi - I get the following error when I try and run `sbt frontendJS/fastOptJS`:
```
➜  task-matrix git:(develop_plus_task-matrix) ✗ sbt frontendJS:fastOptJS
[info] welcome to sbt 1.5.3 (Oracle Corporation Java 11.0.10)
[info] loading settings for project task-matrix-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /Users/coliny/Dev/com.qfi.health/src/scala/task-matrix/project
[info] loading settings for project task-matrix from build.sbt ...
[info] set current project to task-matrix (in build file:/Users/coliny/Dev/com.qfi.health/src/scala/task-matrix/)
[error] No such setting/task
[error] frontendJS:fastOptJS
[error]                     ^
```

To reproduce:
1. ` sbt new yurique/scala-js-laminar-starter.g8`
2. `cd <new project>`
2. `npm install`
3. `sbt frontendJS/fastOptJS`
4. Feel sad :-)

Any suggestions? Thanks!

**Comment by yurique** [comment]
Hi, thanks for bringing this up!

The README was outdated (and the tailwind config) – after a recent change, the frontend sbt module is just `frontend`, not `frontendJS`. So the command should now be `sbt frontend/fastLinkJS` (`fastOptJS` will work as well, but it's been replaced by `fastLinkJS` at some point).

I've updated the template, can you give it another run? :)

**Comment by yatesco** [comment]
Works like a charm - thank you :-)
